### ISSUE TITLE
WHAT'S THE VERSION 1.14.514?

### ISSUE THREAD

**Issue by mcwuguodadi** [Nova-Committee/BANG#1]
MY GAME WAS CRASH IN VERSION "[Fabric 22w13oneBlockAtATime] 1.14.514-build.ああああああああ".

PLEASE REPAIR IT.

ERROR LOG IS [HERE](https://b23.tv/J6SJBT3)

PLEASE READ IT QUICKLY!

MY SYSTEM:WINDOWS 114514

AND STRAT ON:PCL Pro Max Super Plus Ver. X™

MINECRAFT VERSION:22w13oneBlockAtATime WITH FABRIC 0.13.3 AND FABRIC API 0.48.1

NO MORE INFORMATION

(HAHAHAHAHAHAHAHAHA()

**Comment by moechakucha** [comment]
you must be dreaming
its impossible to occur game-crashing bugs in this major update hahaye
its just as perfect as 20w14infinite:)

**Comment by VulpesStella** [comment]
WTF is peakstep doing now👀

**Comment by mcwuguodadi** [comment]
Yes,i'm dreaming now(
